version: '2'

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    networks:
      - arm-mreza
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wt22

  nodejsapp:
    image: vgrbo1/arm:nodejsapp
    container_name: nodejsapp
    ports:
      - "3000:3000"
    networks:
      - arm-mreza
    depends_on:
      - mysql-db
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 20

networks:
  arm-mreza:
    name: arm-mreza
    driver: bridge
